apiVersion: v1
kind: Service
metadata:
  name: foo
spec:
  ports:
  - port: 6004
  type: LoadBalancer
  selector:
    app: foo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
spec:
  selector:
    matchLabels:
      app: foo
  replicas: 1
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
      - name: bar
        image: baz
        ports:
          - containerPort: 6004
